### ISSUE TITLE
Inquiring about choice of activation function

### ISSUE THREAD

**Issue by rakeshKM** [nathanhubens/Autoencoders#2]

**Comment by rakeshKM** [comment]
Hi Nathan, Just a quick question, is there any logic behind the choice of sigmoid being the activation function in lats layer of AE. ?

**Comment by nathanhubens** [comment]
> Hi Nathan, Just a quick question, is there any logic behind the choice of sigmoid being the activation function in lats layer of AE. ?

Hi ! Yes the sigmoid ensures that your output values are between 0 and 1, as it should be because they are pixel values.
